# -*- coding: utf-8 -*-

##  ================
##  Errors Constants
##  ================

ERROR_ABSTRACT = None

##  ==============
##  Checker Errors
##  ==============

CHECKER_OK = 'OK'
CHECKER_CRCERROR = 'CHECKER INVALID DATA STRUCTURE'

ERROR_CHECKER_INVALID_TYPE   = 'INVALID TYPE'
ERROR_CHECKER_BAD_INTEGER    = 'BAD INTEGER'
ERROR_CHECKER_BAD_NUMBER     = 'BAD NUMBER'
ERROR_CHECKER_BAD_TEXT       = 'BAD TEXT'
ERROR_CHECKER_BAD_SIZE       = 'BAD SIZE'
ERROR_CHECKER_IS_EMPTY       = 'EMPTY'
ERROR_CHECKER_EXISTS         = 'EXISTS'

ERROR_CHECKER_BAD_PAN16      = 'BAD PAN16'
ERROR_CHECKER_BAD_PAN19      = 'BAD PAN19'
ERROR_CHECKER_BAD_PANWIDE16  = 'BAD PANWIDE16'
ERROR_CHECKER_BAD_PANWIDE19  = 'BAD PANWIDE19'
ERROR_CHECKER_BAD_EXPIREDATE = 'BAD EXPIREDATE'
ERROR_CHECKER_BAD_BIN        = 'BAD BIN'
ERROR_CHECKER_BAD_EMBOSSNAME = 'BAD EMBOSSNAME'
ERROR_CHECKER_BAD_EAN        = 'BAD EAN'
ERROR_CHECKER_INVALID_VALUE  = 'INVALID VALUE'

ERROR_OUT_OF_SERVICE = 'OS'

##  ===================
##  Handler Return Code
##  ===================

HANDLER_CODE_UNDEFINED = -1
HANDLER_CODE_SUCCESS = 1
HANDLER_CODE_ERROR = 0
