# -*- coding: utf-8 -*-

##  ======================
##  Order Status Constants
##  ======================

STATUS_ABSTRACT             = None

STATUS_ON_INCOMING          = None
STATUS_CREATED              = 1
STATUS_PARAMETERS_CHECKED   = 2
STATUS_DATA_CHECKED         = 3
STATUS_DATA_GENERATED       = 4
STATUS_FILTER_VERIFIED      = 5
STATUS_DATA_VERIFIED        = 6
STATUS_ACCEPTED             = 7
STATUS_DATA_SORTED          = 36
STATUS_BANKCHIP_READY       = 46
STATUS_READY                = 62
STATUS_FINISHED             = 198

STATUS_REJECTED_ERROR       = 201
STATUS_REJECTED_DUBLICATE   = 202
STATUS_REJECTED_EMPTY       = 203
STATUS_REJECTED_INVALID     = 214

STATUS_PINGEN_STARTED       = 8
STATUS_MSDP_STARTED         = 10
STATUS_PIN_ENCASH_STARTED   = 17
STATUS_CARD_ENCASH_STARTED  = 27
STATUS_PERSO_STARTED        = 21
STATUS_SDC_STARTED          = 44
STATUS_POST_ONLINE_STARTED  = 69
STATUS_REPORT_GEN_STARTED   = 71

STATUS_PINGEN_FINISHED      = 12
STATUS_MSDP_FINISHED        = 11
STATUS_PIN_ENCASH_FINISHED  = 18
STATUS_CARD_ENCASH_FINISHED = 28
STATUS_PERSO_FINISHED       = 22
STATUS_SDC_FINISHED         = 45
STATUS_POST_ONLINE_FINISHED = 70
STATUS_REPORT_GEN_FINISHED  = 72

STATUS_ON_READY_ACT_GEN     = 61
STATUS_ON_REPORTS_SENDING   = 63
STATUS_ON_CHECK_ICARD       = 78
STATUS_ON_GROUPED           = 97
STATUS_ON_ORDER_WAIT        = 99
STATUS_ON_ARCHIVE_DONE      = 199
STATUS_ON_SUSPENDED         = 255
STATUS_ON_ERROR             = 0

STATUS_EMPTY                = 0